### PR TITLE
Update Dockerfile.local

### PR DESCRIPTION
**Pull request by Sanpme66**
added "factoextra" library in install.packages() list for docker shiny app import error

### CODE REVIEW

**Comment by hsiaoyi0504** [comment]
@Hailey-Z Can you test this one?

**Comment by Hailey-Z** [comment]
Hi @hsiaoyi0504 this works, I also added the "factoextra" package to the normal Dockerfile.

**Review by Hailey-Z — COMMENTED** [review]
That works

**Comment by hsiaoyi0504** [comment]
Thanks for checking that. I will merge it. Thanks for the contribution from @Sanpme66 as well!

**Comment by sooheon** [comment]
This change isn't in place on main as of 3d67743

**Comment by hsiaoyi0504** [comment]
That's a good catch. We will fix it.

**Pull request merged**
